// Tech-stack logos bundled in /public/tech_stacks. Used by the admin Technologies
// logo picker so editors choose a logo by name (no upload needed) — selecting a
// row sets both the image path and a default label.
const TECH_LOGOS = [
  { label: "Angular", img: "/tech_stacks/angular-icon.svg" },
  { label: "Anthropic", img: "/tech_stacks/anthropic.svg" },
  { label: "AWS", img: "/tech_stacks/aws.svg" },
  { label: "ClickHouse", img: "/tech_stacks/clickhouse.svg" },
  { label: "Django", img: "/tech_stacks/django.svg" },
  { label: "Docker", img: "/tech_stacks/docker.svg" },
  { label: "DynamoDB", img: "/tech_stacks/aws-dynamodb.svg" },
  { label: "Elasticsearch", img: "/tech_stacks/elasticsearch.svg" },
  { label: "Expo", img: "/tech_stacks/expo.svg" },
  { label: "Express.js", img: "/tech_stacks/express-js.svg" },
  { label: "FastAPI", img: "/tech_stacks/FastAPI.svg" },
  { label: "Firebase", img: "/tech_stacks/firebase.svg" },
  { label: "Flutter", img: "/tech_stacks/flutter.svg" },
  { label: "GitHub Actions", img: "/tech_stacks/github_actions.svg" },
  { label: "Go", img: "/tech_stacks/go.svg" },
  { label: "Google Cloud", img: "/tech_stacks/google-cloud.svg" },
  { label: "GraphQL", img: "/tech_stacks/graphql.svg" },
  { label: "HuggingFace", img: "/tech_stacks/huggingface.svg" },
  { label: "Ionic", img: "/tech_stacks/Ionic.svg" },
  { label: "Java Spring Boot", img: "/tech_stacks/spring.svg" },
  { label: "Java", img: "/tech_stacks/java.svg" },
  { label: "Jenkins", img: "/tech_stacks/jenkins.svg" },
  { label: "Kotlin", img: "/tech_stacks/kotlin.svg" },
  { label: "Kubernetes", img: "/tech_stacks/kubernetes.svg" },
  { label: "LangChain", img: "/tech_stacks/langchain.svg" },
  { label: "LlamaIndex", img: "/tech_stacks/llamaindex.svg" },
  { label: "Magento", img: "/tech_stacks/magento.svg" },
  { label: "Microsoft Azure", img: "/tech_stacks/azure.svg" },
  { label: "MongoDB", img: "/tech_stacks/mongodb.svg" },
  { label: "MySQL", img: "/tech_stacks/mysql.svg" },
  { label: "Next.js", img: "/tech_stacks/nextjs.svg" },
  { label: "Node.js", img: "/tech_stacks/node-js.svg" },
  { label: "Objective-C", img: "/tech_stacks/apple_objectivec.svg" },
  { label: "Ollama", img: "/tech_stacks/ollama-icon.svg" },
  { label: "OpenAI API", img: "/tech_stacks/openai.svg" },
  { label: "OpenCart", img: "/tech_stacks/opencart.svg" },
  { label: "OWASP", img: "/tech_stacks/owasp.svg" },
  { label: "PHP Laravel", img: "/tech_stacks/laravel.svg" },
  { label: "Pinecone", img: "/tech_stacks/Pinecone.svg" },
  { label: "PostgreSQL", img: "/tech_stacks/postgresql.svg" },
  { label: "Python", img: "/tech_stacks/python.svg" },
  { label: "PyTorch", img: "/tech_stacks/pytorch.svg" },
  { label: "React", img: "/tech_stacks/react.svg" },
  { label: "Redis", img: "/tech_stacks/redis.svg" },
  { label: "Redux", img: "/tech_stacks/redux.svg" },
  { label: "REST APIs", img: "/tech_stacks/rest-api.svg" },
  { label: "scikit-learn", img: "/tech_stacks/scikit-learn.svg" },
  { label: "Shopify", img: "/tech_stacks/shopify.svg" },
  { label: "Storybook", img: "/tech_stacks/storybook.svg" },
  { label: "Supabase", img: "/tech_stacks/supabase.svg" },
  { label: "Swift", img: "/tech_stacks/swift.svg" },
  { label: "Tailwind CSS", img: "/tech_stacks/tailwind.svg" },
  { label: "TensorFlow", img: "/tech_stacks/tensor_flow.svg" },
  { label: "Terraform", img: "/tech_stacks/terraform.svg" },
  { label: "TypeScript", img: "/tech_stacks/typescript.svg" },
  { label: "Vue.js", img: "/tech_stacks/vue-js.svg" },
  { label: "Webpack", img: "/tech_stacks/webpack-icon.svg" },
  { label: "WooCommerce", img: "/tech_stacks/woocommerce.svg" },
  { label: "Xamarin", img: "/tech_stacks/xamarin.svg" },
  { label: "Xcode", img: "/tech_stacks/x_code.svg" },
];

export default TECH_LOGOS;
